App.EndPoints.DokanNetUI/Areas/Seller/Controllers/AuctionController.cs
using App.Domain.Core.DtoModels;
using App.Domain.Core.Services.Admins.Commands;
using App.Domain.Core.Services.Common.Commands;
using App.Domain.Core.Services.Common.Queries;
using App.Domain.Core.Services.Sellers.Commands;
using App.Domain.Core.Services.Sellers.Queries;
using App.EndPoints.DokanNetUI.Areas.Seller.Models.ViewModels;
using AutoMapper;
using Hangfire;
using Microsoft.AspNet.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace App.EndPoints.DokanNetUI.Areas.Seller.Controllers
{
    [Area("Seller")]
    [Authorize(Roles = "SellerRole")]
    public class AuctionController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IGetAuctionsByStoreId _getAuctionsByStore;
        private readonly IGetAuctionProductsByStoreId _getAuctionProductsByStore;
        private readonly ICreateAuction _createAuction;
        private readonly IGetProductById _getProductById;
        private readonly IReduceProductStock _reduceProductStock;
        private readonly IEndOfAuction _endOfAuction;
        private readonly IBackgroundJobClient _backgroundJobClient;

        public AuctionController(IMapper mapper, IGetAuctionsByStoreId getAuctionsByStore,
                                 ICreateAuction createAuction, IGetProductById getProductById,
                                 IGetAuctionProductsByStoreId getAuctionProductsByStore,
                                 IReduceProductStock reduceProductStock, IEndOfAuction endOfAuction,
                                 IBackgroundJobClient backgroundJobClient)
        {
            _mapper = mapper;
            _getAuctionsByStore = getAuctionsByStore;
            _createAuction = createAuction;
            _getProductById = getProductById;
            _getAuctionProductsByStore = getAuctionProductsByStore;
            _reduceProductStock = reduceProductStock;
            _endOfAuction = endOfAuction;
            _backgroundJobClient = backgroundJobClient;
        }


        public async Task<IActionResult> Index(int id, CancellationToken cancellationToken)
        {
            var auctions = _mapper.Map<List<SellerAuctionVM>>(await _getAuctionsByStore.Execute(id, cancellationToken));
            TempData["StoreId"] = id;
            return View(auctions);
        }


        public async Task<IActionResult> Create(int id, CancellationToken cancellationToken)
        {
            var sellerAuctionVM = new SellerCreateAuctionVM()
            {
                StoreId = id,
                Products = await _getAuctionProductsByStore.Execute(id, cancellationToken)
            };
            return View(sellerAuctionVM);
        }

        [HttpPost]
        public async Task<IActionResult> Create(SellerCreateAuctionVM model, CancellationToken cancellationToken)
        {
            if (ModelState.IsValid)
            {
                //The number of auction products should not be more than the number of warehouse products
                if (model.CountOfProducts <= (await _getProductById.Execute(model.ProductId, cancellationToken)).Stock)
                {
                    //start time should not be more than the end time
                    if (model.StartTime < model.EndTime)
                    {
                        //create auction
                        var auctionId = await _createAuction.Execute(_mapper.Map<AuctionDto>(model), cancellationToken);

                        //Reducing the number of stock products to the amount of auction products
                        await _reduceProductStock.Execute(model.CountOfProducts, model.ProductId, cancellationToken);

                        //run end of auction with hangfire
                        _backgroundJobClient.Schedule(() => _endOfAuction.Execute(auctionId, cancellationToken), (model.EndTime - model.StartTime).Value);

                        return RedirectToAction("Index", new { id = model.StoreId });

                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "زمان شروع باید از زمان پایان کوچکتر باشد");
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "تعداد محصول مزایده نباید از موجودی انبار بیشتر باشد");
                }

            }
            model.Products = await _getAuctionProductsByStore.Execute(model.StoreId, cancellationToken);
            return View(model);
        }
    }
}

App.EndPoints.DokanNetUI/Areas/Seller/Views/Auction/Create.cshtml
@model SellerCreateAuctionVM
@{
    ViewData["Title"] = "ایجاد مزایده";
    Layout = "_Layout";
}



<div class="content">
    <div class="dashboard">
        <div class="container">
            <div class="row">
                <!-- partial dashboard -->
                <div class="col-lg-3">
                    <partial name="~/Areas/Seller/Views/Shared/_PartialSellerDashboard.cshtml"></partial>
                </div>
                <!-- end partial dashboard -->
                <!-- content -->
                <div class="col-lg-9">


                    <h3>ایجاد مزایده</h3>
                    <hr />
                    <div class="row">
                        <div class="col-md-4">
                            <form asp-action="Create">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div> 
                                <div class="form-group">
                                    <label asp-for="StoreId" class="control-label"></label>
                                    <input hidden asp-for="StoreId" class="form-control" />
                                    <span asp-validation-for="StoreId" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="ProductId" class="control-label"></label>
                                    <br />
                                    <select required asp-for="ProductId" asp-items="@(new SelectList(Model.Products, nameof(ProductDto.Id), nameof(ProductDto.Title)))" class="form-control">
                                        <option style="display:none;" value="">انتخاب کنید</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label asp-for="CountOfProducts" class="control-label"></label>
                                    <input asp-for="CountOfProducts" class="form-control" />
                                    <span asp-validation-for="CountOfProducts" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="StartTime" class="control-label"></label>
                                    <input asp-for="StartTime" class="form-control" />
                                    <span asp-validation-for="StartTime" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="EndTime" class="control-label"></label>
                                    <input asp-for="EndTime" class="form-control" />
                                    <span asp-validation-for="EndTime" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <input type="submit" value="ایجاد" class="btn btn-primary" />
                                </div>
                            </form>
                        </div>
                    </div>


                    <div>
                        <a asp-action="Index" asp-route-id="@Model.StoreId">بازگشت</a>
                    </div>


                </div>
                <!-- end content -->
            </div>
        </div>
    </div>
</div>



@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

App.EndPoints.DokanNetUI/Areas/Seller/Views/Auction/Index.cshtml
@model List<SellerAuctionVM>
@{
    ViewData["Title"] = "مزایده های من";
    Layout = "_Layout";
}

@*set store id*@
@{
    int storeId = Convert.ToInt32(TempData.Peek("StoreId"));
}


<div class="content">
    <div class="dashboard">
        <div class="container">
            <div class="row">
                <!-- partial dashboard -->
                <div class="col-lg-3">
                    <partial name="~/Areas/Seller/Views/Shared/_PartialSellerDashboard.cshtml"></partial>
                </div>
                <!-- end partial dashboard -->
                <!-- content -->
                <div class="col-lg-9">
                    <div class="content-box" style="padding:40px 20px;">
                        <div class="text-center">

                            <div class="text-center">
                                <a class="btn btn-add-to-cart my-3" asp-area="Seller" asp-controller="Auction" asp-action="Create" asp-route-id="@storeId">ایجاد مزایده جدید</a>
                            </div>
                            <hr />
                            <div class="category-item my-2">
                                <div class="row">

                                    @foreach (var auction in Model)
                                    {
                                        <div class="col-md-4">
                                            <div class="product-box-item shadow-box">
                                                <div class="product-box-item-img">
                                                    <a href="#">
                                                        @if (auction.ProductImages.Count > 0)
                                                        {
                                                            <img src="@auction.ProductImages[0].Url" alt="" class="img-fluid">
                                                        }
                                                        else
                                                        {
                                                            <img src="img/product/wach3.jpg" alt="" class="img-fluid">
                                                        }
                                                    </a>
                                                    @if (auction.HasBuyer)
                                                    {
                                                        <div class="product-box-item-hover">
                                                            <div class="product-box-item-hover-cart">
                                                                <button class="product-box-item-hover-cart-btn">
                                                                    <i class="bi bi-list"></i> لیست خریداران
                                                                </button>
                                                            </div>
                                                        </div>
                                                    }
                                                </div>
                                                <a href="#">
                                                    <div class="product-box-item-desc">
                                                        <div class="product-box-item-title my-1">
                                                            <h5>
                                                                @auction.ProductTitle
                                                            </h5>
                                                        </div>
                                                        <div class="product-box-item-title text-danger">
                                                            <h6 style="height: 35px;">
                                                                تعداد : @auction.CountOfProducts
                                                            </h6>
                                                        </div>
                                                        @if (auction.StartTime > DateTime.Now)
                                                        {
                                                            <span class="badge bg-danger rounded-pill text-white my-flex-center">شروع نشده</span>
                                                        }
                                                        else if (auction.StartTime <= DateTime.Now && auction.EndTime > DateTime.Now)
                                                        {
                                                            <span class="badge bg-danger rounded-pill text-white my-flex-center">در حال انجام</span>
                                                        }
                                                        else if (auction.EndTime <= DateTime.Now)
                                                        {
                                                            <span class="badge bg-danger rounded-pill text-white my-flex-center">تمام شده</span>
                                                        }
                                                        <div class="product-box-price" style="margin-top: 10px; height: 90px;">
                                                            <div class="d-flex justify-content-between">
                                                                <span class=" bg-info rounded-pill text-white my-flex-center">زمان شروع : @auction.StartTime</span>
                                                                <span class=" bg-info rounded-pill text-white my-flex-center">زمان پایان : @auction.EndTime</span>
                                                                <span class="new-price" style="color: #0f8a2e;">
                                                                    قیمت: @auction.Price تومان
                                                                </span>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </a>
                                            </div>
                                        </div>
                                    }

                                </div>
                            </div>
                        </div>

                    </div>
                </div>
                <!-- end content -->
            </div>
        </div>
    </div>
</div>




@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    }